language: ruby
cache:
  bundler: true
  directories:
    # Cache html-proofer results. See: https://github.com/gjtorikian/html-proofer#caching-with-travis
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

script:
- rake test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
