language: ruby
rvm:
- 2.5.3

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-favicon --check-html --url-ignore /linkedin\.com*,codepen\.io*/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
