language: ruby

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-favicon --check-html --url-ignore /linkedin\.com*/,/codepen\.io*/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  directories:
    # Cache html-proofer results. See: https://github.com/gjtorikian/html-proofer#caching-with-travis
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer