language: ruby
rvm:
- 2.1

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-favicon --check-html --url-ignore /linkedin\.com*/,/markmonteiro.info\\\z/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
