language: ruby
cache:
  bundler: true
  directories:
    # Cache html-proofer results. See: https://github.com/gjtorikian/html-proofer#caching-with-travis
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
    # Cache NPM dependencies. See: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm
    - $HOME/.npm

script:
- nvm use
- npm ci
- npm run build:production
- npm test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
