# Github Unmodifiable Settings
safe: true
lsi: false
source: .
markdown: kramdown
highlighter: rouge
# github: [Repository metadata]

# SEO Settings
title: Mark Monteiro
description: Mark Monteiro is a software engineer and web developer recently graduated from the University of Waterloo. This is his personal resume website.
url: https://markmonteiro.info
logo: /favicon-194x194.png
google_analytics_code: UA-7688784-3

# Custom Settings
homepage: index.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  
collections:
  - projects
  - experiences

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer
